src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingManager.cs
src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs

This is a joint work with the Solaris team (it still needs some testing)
The active PR can be found here
https://github.com/SolarisPlatform/SolarisBitcoinFullNode/pull/3

Recover cold accounts when recovering a wallet

---

src/FederationSetup/GenesisMiner.cs
src/Stratis.Bitcoin.Features.Consensus.Tests/StakeValidatorTests.cs
src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletRPCControllerTest.cs
src/Stratis.Features.FederatedPeg.Tests/Wallet/FederationWalletManagerTests.cs
src/Stratis.Features.FederatedPeg/TargetChain/SigningUtils.cs
src/Stratis.Features.FederatedPeg/TargetChain/WithdrawalHistoryProvider.cs
src/Stratis.Features.FederatedPeg/Wallet/FederationWalletManager.cs
src/Stratis.Features.SQLiteWalletRepository/External/ITransactionsToLists.cs
src/Stratis.Sidechains.Networks/CirrusNetwork.cs
src/Stratis.SmartContracts.CLR.Tests/ContractTransferProcessorTests.cs
src/Stratis.SmartContracts.CLR/ResultProcessors/ContractTransferProcessor.cs
src/Stratis.SmartContracts.Core/ContractTransactionContext.cs
src/Stratis.SmartContracts.Core/State/AccountAbstractionLayer/TransactionCondenser.cs
src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractWalletOnPosNetworkTests.cs
src/Stratis.SmartContracts.Networks/SmartContractNetworkUtils.cs

This will get sidechains (fed peg) and smart contracts to compile again
This fix was created by @zeptin in another branch

Fix the Stratis.Bitcoin.FullNode solution 

---

src/NBitcoin.Tests/NetworkTests.cs
src/NBitcoin/BIP9Deployments.cs
src/NBitcoin/Consensus.cs
src/NBitcoin/IConsensus.cs
src/Stratis.Bitcoin.Features.ColdStaking.Tests/ColdStakingControllerTest.cs
src/Stratis.Bitcoin.Features.Miner.Tests/PosBlockAssemblerTest.cs
src/Stratis.Bitcoin.Features.Miner.Tests/PowBlockAssemblerTest.cs
src/Stratis.Bitcoin.Features.PoA/PoANetwork.cs
src/Stratis.Bitcoin.Features.RPC/Controllers/FullNodeController.cs
src/Stratis.Bitcoin.IntegrationTests/ColdStakingTests.cs
src/Stratis.Bitcoin.IntegrationTests/SegWitTests.cs
src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletRPCControllerTest.cs
src/Stratis.Bitcoin.Networks/BitcoinMain.cs
src/Stratis.Bitcoin.Networks/BitcoinRegTest.cs
src/Stratis.Bitcoin.Networks/BitcoinTest.cs
src/Stratis.Bitcoin.Networks/StratisMain.cs
src/Stratis.Bitcoin.Networks/StratisRegTest.cs
src/Stratis.Bitcoin.Networks/StratisTest.cs
src/Stratis.Bitcoin/Base/Deployments/Models/ThresholdStateModel.cs
src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs
src/Stratis.Sidechains.Networks/CirrusMain.cs
src/Stratis.Sidechains.Networks/CirrusRegTest.cs
src/Stratis.Sidechains.Networks/CirrusTest.cs
src/Stratis.SmartContracts.Networks/SmartContractPosRegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractsPoARegTest.cs
src/Stratis.SmartContracts.Networks/SmartContractsRegTest.cs

Replaces https://github.com/block-core/blockcore/pull/34

Merge bip 9

---

src/Stratis.Bitcoin.Features.Miner.Tests/Controllers/StakingControllerTest.cs
src/Stratis.Bitcoin.Features.Miner/Controllers/StakingController.cs
src/Stratis.Bitcoin.Features.Miner/MinerSettings.cs
src/Stratis.Bitcoin.Features.Miner/Models/RequestModels.cs
src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs
src/Stratis.Bitcoin.Features.Wallet/Wallet.cs

@thecrypt0hunter any chance you can help with testing this?

White-list staking addresses

---

.github/workflows/build.yml
.github/workflows/integration-test.yml

This is in reference to PR https://github.com/block-core/blockcore/pull/35

Update GitHub Actions to use dotnet 3.1

---

.github/workflows/publish-pre-release.yml
src/NBitcoin/NBitcoin.csproj

Fixed publish pre-release versioning and added NBitcoin Developers to authors of NBitcoin

Fixed publish pre-release versioning

---

src/Stratis.Bitcoin/Controllers/NodeController.cs

This fixes issue https://github.com/block-core/blockcore/issues/57

Fixed the address validation.

---

src/NBitcoin.Tests/uint256_tests.cs
src/NBitcoin/BitcoinStream.Partial.cs
src/NBitcoin/BitcoinStream.cs
src/NBitcoin/Protocol/VarInt.cs
src/NBitcoin/UInt256.cs
src/NBitcoin/Utils.cs

Use span for uint256 which should improve performance and memory consumption of the full node.
https://github.com/MetacoSA/NBitcoin/commit/8864a47aaf22f11769d65ade609d38d18f90faa7#diff-6b972e431df706b91757f5c8f0bc3229

Port in NBitcoin uint256 span

---

.github/workflows/publish-pre-release.yml
src/Blockcore.Features.ColdStaking/Directory.Build.props
src/Blockcore.Features.Diagnostic/Blockcore.Features.Diagnostic.csproj
src/Blockcore.Features.Diagnostic/Directory.Build.props
src/Blockcore.Features.SignalR/Blockcore.Features.SignalR.csproj
src/Blockcore.Features.SignalR/Directory.Build.props

Added Directory.Build.props for missing packages (ColdStaking/Diagnostic/SignalR).
Added a "." to the version suffix for pre release packages to ensure correct version ordering.

Updates for missing packages and fix to pre-release versioning

---

CHANGELOG.md
package.json
src/Blockcore/Blockcore.csproj
src/External/Blockcore.Benchmark/Blockcore.Benchmark.csproj
src/External/NBitcoin.Tests/NBitcoin.Tests.csproj
src/Features/Blockcore.Features.BlockStore/Blockcore.Features.BlockStore.csproj
src/Features/Blockcore.Features.Consensus/Blockcore.Features.Consensus.csproj
src/Features/Blockcore.Features.MemoryPool/Blockcore.Features.MemoryPool.csproj
src/Features/Blockcore.Features.Miner/Blockcore.Features.Miner.csproj
src/Features/Blockcore.Features.NodeHost/Blockcore.Features.NodeHost.csproj
src/Features/Blockcore.Features.RPC/Blockcore.Features.RPC.csproj
src/Features/Blockcore.Features.Wallet/Blockcore.Features.Wallet.csproj
src/Tests/Blockcore.Features.BlockStore.Tests/Blockcore.Features.BlockStore.Tests.csproj
src/Tests/Blockcore.Features.ColdStaking.Tests/Blockcore.Features.ColdStaking.Tests.csproj
src/Tests/Blockcore.Features.Consensus.Tests/Blockcore.Features.Consensus.Tests.csproj
src/Tests/Blockcore.Features.Dns.Tests/Blockcore.Features.Dns.Tests.csproj
src/Tests/Blockcore.Features.MemoryPool.Tests/Blockcore.Features.MemoryPool.Tests.csproj
src/Tests/Blockcore.Features.Miner.Tests/Blockcore.Features.Miner.Tests.csproj
src/Tests/Blockcore.Features.NodeHost.Tests/Blockcore.Features.NodeHost.Tests.csproj
src/Tests/Blockcore.Features.PoA.Tests/Blockcore.Features.PoA.Tests.csproj
src/Tests/Blockcore.Features.RPC.Tests/Blockcore.Features.RPC.Tests.csproj
src/Tests/Blockcore.Features.Wallet.Tests/Blockcore.Features.Wallet.Tests.csproj
src/Tests/Blockcore.IntegrationTests/Blockcore.IntegrationTests.csproj
src/Tests/Blockcore.Tests.Common/Blockcore.Tests.Common.csproj
src/Tests/Blockcore.Tests/Blockcore.Tests.csproj

- DNS, Microsoft.FASTER and LiteDB not upgraded.

Upgrade packages to latest versions

---

src/External/NBitcoin/Protocol/Versions.cs
src/Features/Blockcore.Features.MemoryPool/Blockcore.Features.MemoryPool.csproj
src/Features/Blockcore.Features.MemoryPool/FeeFilter/FeeFilterBehavior.cs
src/Features/Blockcore.Features.MemoryPool/FeeFilter/FeeFilterPayload.cs
src/Features/Blockcore.Features.MemoryPool/MempoolBehavior.cs
src/Features/Blockcore.Features.MemoryPool/MempoolFeature.cs
src/Features/Blockcore.Features.MemoryPool/MempoolManager.cs
src/Features/Blockcore.Features.MemoryPool/MempoolSettings.cs
src/Features/Blockcore.Features.MemoryPool/MempoolValidator.cs
src/Features/Blockcore.Features.MemoryPool/TxMemPool.cs
src/Networks/Bitcoin/Blockcore.Networks.Bitcoin/BitcoinMain.cs

This PR introduces the FeeFilter support (BIP113) protocol version 70015
The peer will tell us what is their max fee rate limit and our peer will not send invs trx bellow that fee.
Issue #118

Add FeeFilter capabilities protocol version 70013

---

src/Features/Blockcore.Features.Wallet/UI/Pages/WalletSend.razor

- Fix error & improve coins sent message

UI Fixes & Updates

---

src/Features/Blockcore.Features.NodeHost/UI/Pages/About.razor
src/Features/Blockcore.Features.NodeHost/UI/Pages/Index.razor
src/Features/Blockcore.Features.NodeHost/UI/Pages/_Host.cshtml
src/Features/Blockcore.Features.NodeHost/UI/Shared/Dropdown.razor
src/Features/Blockcore.Features.NodeHost/UI/Shared/DropdownListItem.razor
src/Features/Blockcore.Features.NodeHost/UI/Shared/NavMenu.razor

- Add Logo to nav menu
- Add about page with links to swagger, web socket & blockcore website

Add About Page

---

src/Features/Blockcore.Features.ColdStaking/UI/Pages/ColdStakeWithdraw.razor
src/Features/Blockcore.Features.Wallet/UI/Pages/WalletSend.razor

- Removes parameters after send
- Adds a button to navigate to wallet page
- Add spinner & disable button whilst withdrawing from cold staking

Remove parameters after coins sent 

---

src/Features/Blockcore.Features.Consensus/Rules/CommonRules/CheckPowTransactionRule.cs

Improvement on CVE-2018-17144 rule check

---

src/Features/Blockcore.Features.Wallet/Api/Controllers/WalletModelBuilder.cs

Added segwit address to request query for wallet history

Added the Bech32Address as a query for history

---

.github/workflows/build.yml

To fix the depreciated workflow set-env causing the build to fail

 Updated CI Var for GitHub workflow change.

---

.github/workflows/build.yml

Work around from: https://github.com/actions/setup-dotnet/issues/155

Fix build error: NU1101: Unable to find package

---

.github/workflows/build.yml

Add upload of artifact to the build

---

src/Networks/Blockcore.Networks.City/Blockcore.Networks.City.csproj
src/Networks/Blockcore.Networks.Impleum/Blockcore.Networks.Impleum.csproj
src/Networks/Blockcore.Networks.OpenExo/Blockcore.Networks.OpenExo.csproj
src/Networks/Blockcore.Networks.Rutanio/Blockcore.Networks.Rutanio.csproj
src/Networks/Blockcore.Networks.Stratis/Blockcore.Networks.Stratis.csproj
src/Networks/Blockcore.Networks.X1/Blockcore.Networks.X1.csproj
src/Networks/Blockcore.Networks.XRC/Blockcore.Networks.XRC.csproj
src/Networks/Blockcore.Networks.Xds/Blockcore.Networks.Xds.csproj
src/Networks/Blockcore.Networks.x42/Blockcore.Networks.x42.csproj

- This will customize the icons on NuGet listings.

Add the package icon to network packages

---

src/Networks/Blockcore.Networks.XRC/Consensus/XRCConsensusFactory.cs
src/Networks/Blockcore.Networks.XRC/XRCMain.cs

Based on feedback from discord I did some changes. Thanks

Refactoring of xRhodium XRC network configuration

---

src/Networks/Blockcore.Networks.City/Networks/CityMain.cs
src/Networks/Blockcore.Networks.City/Networks/CityRegTest.cs
src/Networks/Blockcore.Networks.City/Networks/CityTest.cs
src/Networks/Blockcore.Networks.City/Networks/Deployments/CityBIP9Deployments.cs

- Needed for proper indicator in the Node UI.

Update the BIP9 deployment flags

---

src/Features/Blockcore.Features.Wallet/Api/Controllers/WalletController.cs
src/Tests/Blockcore.Features.Wallet.Tests/WalletControllerTest.cs

Use the Slim method for api/wallet/history

---

src/Features/Blockcore.Features.Wallet/Api/Controllers/WalletModelBuilder.cs
src/Features/Blockcore.Features.Wallet/Api/Models/WalletHistoryModel.cs
src/Networks/Blockcore.Networks.HomeCoin/HomeCoinSetup.cs
src/Networks/Blockcore.Networks.HomeCoin/Networks/HomeCoinMain.cs

Small improvements to Web API to determine transfers to own addresses

Small improvements to Web API

---

src/Features/Blockcore.Features.Wallet/Api/Controllers/WalletController.cs

Use the full history query for wallet history API

---

src/Networks/Blockcore.Networks.City/CitySetup.cs
src/Networks/Blockcore.Networks.City/Networks/CityMain.cs

- Due to delay in release of Blockcore, delay the start of activation.

Activate the beginning of activation the 12th of April

---

.github/workflows/build.yml

- Remove the duplicate upload for Ubuntu.
- Add the OS to filename to make different artifacts.

Fix artifact upload

---

src/Blockcore/Base/BaseFeature.cs
src/Node/Blockcore.Node/Properties/launchSettings.json

- The .Tip is null if the "FlushChain" is run before reindex has completed.

Fixes an issue when reindex takes more than one minute

---

src/Features/Persistence/Blockcore.Persistence.RocksDb/Blockcore.Persistence.RocksDb.csproj
src/Tests/Blockcore.Features.BlockStore.Tests/Blockcore.Features.BlockStore.Tests.csproj
src/Tests/Blockcore.IntegrationTests/Blockcore.IntegrationTests.csproj

- Upgrade our own RocksDB package used for persistance.
- Remove unused older RocksDB package.

Update the RocksDB package

---

src/Blockcore/Utilities/JsonConverters/ScriptCollectionJsonConverter.cs
src/Features/Blockcore.Features.ColdStaking/ColdStakingManager.cs
src/Features/Blockcore.Features.Miner/Staking/PosMinting.cs
src/Features/Blockcore.Features.Wallet/Types/Wallet.cs
src/Networks/Blockcore.Networks.X1/Components/X1PosMinting.cs
src/Tests/Blockcore.Features.ColdStaking.Tests/ColdStakingControllerTest.cs

This PR fixes a cold stake bug found recently where hot/cold keys are use in more then one redeem script
https://github.com/block-core/blockcore/issues/395

Coldstake redeem bug

---

src/Networks/Blockcore.Networks.XRC/Rules/XRCCheckDifficultyPowRule.cs

Hello,
we are so sorry but we found issue in latest code which blocking synchronization with official XRC node.
There is a fix.
Thank you for merge.

Synced PowLimit condition with Official XRC Node

---

src/Networks/Blockcore.Networks.RoyalSportsCity/Networks/RoyalSportsCityRegTest.cs
src/Networks/Blockcore.Networks.RoyalSportsCity/Networks/RoyalSportsCityTest.cs
src/Networks/Blockcore.Networks.RoyalSportsCity/RoyalSportsCitySetup.cs
src/Networks/Blockcore.Networks.SeniorBlockCoin/Networks/SeniorBlockCoinRegTest.cs
src/Networks/Blockcore.Networks.SeniorBlockCoin/Networks/SeniorBlockCoinTest.cs

Test networks have not yet been run by anyone and we now intend to set them up. That's why they needed change.
Thanks for accepting these changes

Update TSBC Consensus and TRSC Consensus

---

src/Features/Blockcore.Features.ColdStaking/ColdStakingFeature.cs
src/Features/Blockcore.Features.ColdStaking/ColdStakingManager.cs
src/Features/Blockcore.Features.ColdStaking/UI/CopyToClipboard.razor
src/Features/Blockcore.Features.ColdStaking/UI/NavItem.cs
src/Features/Blockcore.Features.ColdStaking/UI/Pages/ColdStake.razor
src/Features/Blockcore.Features.ColdStaking/UI/Pages/ColdStakeAccounts.razor
src/Features/Blockcore.Features.ColdStaking/UI/Pages/ColdStakeDelegate.razor
src/Features/Blockcore.Features.ColdStaking/UI/Pages/ColdStakePool.razor
src/Features/Blockcore.Features.ColdStaking/UI/Pages/ColdStakePoolView.razor
src/Features/Blockcore.Features.ColdStaking/UI/Pages/ColdStakeReceive.razor
src/Features/Blockcore.Features.ColdStaking/UI/Pages/ColdStakeSetup.razor
src/Features/Blockcore.Features.ColdStaking/UI/Pages/ColdStakeView.razor
src/Features/Blockcore.Features.ColdStaking/UI/Pages/Modal/ModalViewPoolTransaction.razor
src/Features/Blockcore.Features.Miner/Api/Controllers/StakingController.cs
src/Features/Blockcore.Features.Miner/Api/Models/GetStakingAddressesModel.cs
src/Features/Blockcore.Features.Miner/Api/Models/RequestModels.cs
src/Features/Blockcore.Features.Miner/MinerSettings.cs
src/Features/Blockcore.Features.Miner/Staking/PosMinting.cs
src/Features/Blockcore.Features.Miner/UI/Pages/Stake.razor
src/Features/Blockcore.Features.Wallet/Helpers/HdOperations.cs
src/Features/Blockcore.Features.Wallet/Types/Wallet.cs
src/Features/Blockcore.Features.Wallet/UI/Pages/WalletReceive.razor
src/Node/Blockcore.Node/Properties/launchSettings.json

The intention behind staking pool is to enable anyone to become a cold staking pool provider and be able to manage the pool.

Preparing for cold staking pools

---

src/Blockcore/Builder/FullNodeBuilder.cs
src/Blockcore/Builder/IFullNodeBuilderServiceOverride.cs
src/Blockcore/Networks/Network.cs
src/Networks/Blockcore.Networks.Strax/Staking/MiningServiceOverride.cs
src/Networks/Blockcore.Networks.Strax/StraxMain.cs
src/Networks/Blockcore.Networks.Strax/StraxRegTest.cs
src/Networks/Blockcore.Networks.Strax/StraxTest.cs

I am not totally sure this is the right location to put the override class, suggestions are welcome.

Add an interface to override services from the network class

---

src/Blockcore/Blockcore.csproj
src/Features/Blockcore.Features.NodeHost/Blockcore.Features.NodeHost.csproj
src/Features/Blockcore.Features.RPC/Blockcore.Features.RPC.csproj
src/Features/Blockcore.Features.Wallet/Blockcore.Features.Wallet.csproj

Microsoft.AspNetCore.Mvc.NewtonsoftJson@8.0.3
Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson#8.0.3
Microsoft.Data.Sqlite@8.0.3
Polly@8.3.1
Dapper@2.1.35

Libraries upgrade 2
