src/Stratis.Bitcoin.Features.RPC.Tests/Controller/WalletRPCControllerTests.cs, src/Stratis.Bitcoin.Features.RPC/RPCOperations.cs, src/Stratis.Bitcoin.Features.RPC/RPCParametersValueProvider.cs, src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs, src/Stratis.Bitcoin.Features.Wallet/Models/ListSinceBlockModel.cs, src/Stratis.Bitcoin.Features.Wallet/Models/ListSinceBlockTransactionModel.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs, src/Stratis.Bitcoin.Features.Wallet/WalletRPCController.cs, src/Stratis.Bitcoin.IntegrationTests/API/ApiSteps.cs
- Change getnewaddress method so that it will always generate a new address
- Add listsinceblock method
=> RPC add method listsinceblock,getunusedaddress and change getnewaddress

src/Stratis.Bitcoin.Features.ColdStaking.Tests/ColdStakingControllerTest.cs, src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingManager.cs, src/Stratis.Bitcoin.Features.ColdStaking/Controllers/ColdStakingController.cs, src/Stratis.Bitcoin.Features.ColdStaking/Models/ColdStakingModels.cs, src/Stratis.Bitcoin.Features.Miner/Staking/PosMinting.cs, src/Stratis.Bitcoin.Features.Wallet/Wallet.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs, src/Stratis.Bitcoin.Features.Wallet/WalletTransactionHandler.cs, src/Stratis.Bitcoin.Networks/Policies/StratisStandardScriptsRegistry.cs
This PR originated in the ObsidianX fork as an attempt to make the ODX network use segwit only consensus.
This will allow to coldstake with a P2WSH (or a P2SH) and provide the cold stake special ScriptPubKey as a redeem script in the inputs WitScript part of the coinstake transaction.
https://github.com/obsidianproject/Obsidian-StratisNode/pull/47
https://github.com/block-core/blockcore/issues/12
=> Adding script hash staking

src/Stratis.Bitcoin.Features.ColdStaking/ColdStakingManager.cs, src/Stratis.Bitcoin.Features.Miner.Tests/PosMintingTest.cs, src/Stratis.Bitcoin.Features.SignalR/Broadcasters/WalletInfoBroadcaster.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/AccountRootTest.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/HdAccountTest.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletControllerTest.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletManagerTest.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTest.cs, src/Stratis.Bitcoin.Features.Wallet.Tests/WalletTestBase.cs, src/Stratis.Bitcoin.Features.Wallet/AddressBalance.cs, src/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs, src/Stratis.Bitcoin.Features.Wallet/Interfaces/IWalletManager.cs, src/Stratis.Bitcoin.Features.Wallet/KnownCoinTypes.cs, src/Stratis.Bitcoin.Features.Wallet/Models/AddressBalanceModel.cs, src/Stratis.Bitcoin.Features.Wallet/Models/RequestModels.cs, src/Stratis.Bitcoin.Features.Wallet/Models/WalletBalanceModel.cs, src/Stratis.Bitcoin.Features.Wallet/Models/WalletHistoryModel.cs, src/Stratis.Bitcoin.Features.Wallet/Wallet.cs, src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletAddressGenerationAndFundsVisibility_Steps.cs, src/Stratis.Bitcoin.IntegrationTests/Wallet/WalletOperationsTests.cs, src/Stratis.Bitcoin.Tests.Common/KnownCoinTypes.cs, src/Stratis.Bitcoin.Tests.Wallet.Common/WalletTestsHelpers.cs
**Purpose** 
This PR is to allow the creation of wallets with a different account type from the default specified in Network.
**Usage and use-case**
This is useful for airdrop scenarios where coin are airdropped on private keys in a derivation path that belongs to another coin.
**Testing**
- Wallet integration tests passed
- Wallet Unit tests passed
- This is not properly tested yet (it will be tested as part of the ObsidianX airdrop testing)
=> Extend wallet account type

src/Stratis.Bitcoin.Features.Wallet/Wallet.cs
With this change, the message is successfully signed, but the message is signed with the paired base58 address not the Bech32 address, so in order to validate the message, the user needs to validate from the base58 not the Bech32Address.
Is there a way we can sign with the Bech32 address and not the underlying base58 address?
If there is not a better way, I would suggest that the base58 address is returned with the signature string.
=> Fix segwit sign message

README.md
- Make sure that anyone looking into Blockcore that the best starting point is our blockcore-node repository.
=> Add a note to direct users to blockcore-node

src/Blockcore/Consensus/FinalizedBlockInfoRepository.cs, src/Features/Blockcore.Features.Consensus/ProvenBlockHeaders/RewindDataIndexCache.cs
Finality is ahead of consensus if the node crashed.
In this case we just load the rewind data as usual with data going back from current consensus and ignore finality (it will become overriden on next block)
=> If finality is ahead of consensus don't fail the indexer.

src/Features/Blockcore.Features.ColdStaking/ColdStakingManager.cs, src/Features/Blockcore.Features.SignalR/Broadcasters/WalletInfoBroadcaster.cs, src/Features/Blockcore.Features.Wallet/Controllers/WalletController.cs, src/Features/Blockcore.Features.Wallet/Controllers/WalletRPCController.cs, src/Features/Blockcore.Features.Wallet/Events/TransactionFound.cs, src/Features/Blockcore.Features.Wallet/Models/GetWalletInfoModel.cs, src/Features/Blockcore.Features.Wallet/Wallet.cs, src/Features/Blockcore.Features.Wallet/WalletManager.cs, src/Networks/City/City/Networks/CityMain.cs, src/Networks/City/City/Networks/Consensus/CityPosConsensusOptions.cs, src/Tests/Blockcore.Features.ColdStaking.Tests/ColdStakingControllerTest.cs, src/Tests/Blockcore.Features.ColdStaking.Tests/ColdStakingManagerTest.cs, src/Tests/Blockcore.Features.Wallet.Tests/WalletManagerTest.cs, src/Tests/Blockcore.IntegrationTests/API/ApiSteps.cs
- Add a signal when transactoin is found in wallet.
- Add options to filter what is returned from Accounts,  Transactions and Balances.
=> Add signal when transaction found in wallet, and filtering on wallet

src/Blockcore.sln, src/Node/Blockcore.Node/Blockcore.Node.csproj, src/Node/Blockcore.Node/NetworkSelector.cs, src/Node/Blockcore.Node/NodeBuilder.cs, src/Node/Blockcore.Node/Program.cs, src/Node/Blockcore.Node/Properties/launchSettings.json
- Adds a new project that can launch multiple chains based on startup argument. This allows us to remove the existing node projects, they are no longer needed.
=> Add Blockcore.Node project for quick and easy debug of multiple chains

src/Blockcore/BlockPulling/BlockPuller.cs, src/Blockcore/Configuration/NodeSettings.cs, src/Blockcore/Connection/ConnectionManager.cs, src/Blockcore/Controllers/NodeController.cs, src/Blockcore/P2P/PeerConnector.cs, src/External/NBitcoin/Consensus.cs, src/External/NBitcoin/ConsensusFactory.cs, src/External/NBitcoin/IConsensus.cs, src/Features/Blockcore.Features.PoA/PoANetwork.cs, src/Features/Blockcore.Features.RPC/Controllers/FullNodeController.cs, src/Networks/Bitcoin/Blockcore.Networks.Bitcoin/BitcoinMain.cs, src/Networks/Bitcoin/Blockcore.Networks.Bitcoin/BitcoinRegTest.cs, src/Networks/Bitcoin/Blockcore.Networks.Bitcoin/BitcoinTest.cs, src/Networks/City/City/Networks/CityMain.cs, src/Networks/City/City/Networks/CityRegTest.cs, src/Networks/City/City/Networks/CityTest.cs, src/Networks/Stratis/Blockcore.Networks.Stratis/StratisMain.cs, src/Networks/Stratis/Blockcore.Networks.Stratis/StratisRegTest.cs, src/Networks/Stratis/Blockcore.Networks.Stratis/StratisTest.cs, src/Networks/Xds/Blockcore.Networks.Xds/XdsMain.cs, src/Networks/x42/x42/Networks/Consensus/x42Consensus.cs, src/Networks/x42/x42/Networks/x42Main.cs, src/Networks/x42/x42/Networks/x42RegTest.cs, src/Networks/x42/x42/Networks/x42Test.cs, src/Tests/Blockcore.Features.RPC.Tests/Controller/FullNodeControllerTest.cs, src/Tests/Blockcore.IntegrationTests/API/ApiSteps.cs, src/Tests/Blockcore.IntegrationTests/RPC/GetInfoActionTests.cs
VersionProtocol is partly used in  determining serialization it makes more sense to keep it in the consensus factory.
=> Move protocol out of the consensus class and in to the consensus factory

src/Blockcore/BlockPulling/BlockPuller.cs, src/Blockcore/P2P/Peer/NetworkPeerConnectionParameters.cs, src/Blockcore/P2P/Peer/NetworkPeerFactory.cs, src/Blockcore/P2P/PeerConnector.cs, src/Blockcore/P2P/Protocol/Payloads/GetBlocksPayload.cs, src/Blockcore/P2P/Protocol/Payloads/GetHeadersPayload.cs, src/External/NBitcoin/Protocol/Versions.cs, src/Tests/Blockcore.IntegrationTests.Common/EnvironmentMockUpHelpers/CoreNode.cs, src/Tests/Blockcore.IntegrationTests.Common/EnvironmentMockUpHelpers/NodeBuilder.cs, src/Tests/Blockcore.IntegrationTests.Common/Runners/CustomRunner.cs, src/Tests/Blockcore.IntegrationTests/CustomNodeBuilderTests.cs, src/Tests/Blockcore.IntegrationTests/ProofOfStakeSteps.cs, src/Tests/Blockcore.Tests/Base/ConsensusManagerBehaviorTests.cs, src/Tests/Blockcore.Tests/P2P/NetworkPeerServerTests.cs, src/Tests/Blockcore.Tests/P2P/NetworkPeerTests.cs
Remove the const PROTOCOL_VERSION and use the version per chain on the consensus factory instead, this will prevent mixing protocol version between chains.
=> Remove the const PROTOCOL_VERSION 

src/Features/Blockcore.Features.BlockStore/Models/SignMessageResult.cs, src/Features/Blockcore.Features.Wallet/Api/Controllers/WalletController.cs, src/Features/Blockcore.Features.Wallet/Interfaces/IWalletManager.cs, src/Features/Blockcore.Features.Wallet/WalletManager.cs, src/Tests/Blockcore.IntegrationTests/Wallet/WalletOperationsTests.cs
This is a follow up to PR https://github.com/block-core/blockcore/pull/66 where I said:
> Is there a way we can sign with the Bech32 address and not the underlying base58 address?
> 
> If there is not a better way, I would suggest that the base58 address is returned with the signature string.
This is the PR for that suggestion as that PR was committed without any further input, so this will provide a solution until a better solution is presented.
=> When segwit address is used to sign, we need to return the address signed with.

src/Features/Blockcore.Features.Wallet/WalletTransactionHandler.cs
If the network consensus has no fee's, we need to allow GetMaximumSpendableAmount to continue.
=> Allow zero fee's while estimating spendable amount.

src/Features/Blockcore.Features.BlockStore/Api/BlockStoreClient.cs, src/Features/Blockcore.Features.BlockStore/Api/Controllers/BlockStoreController.cs, src/Features/Blockcore.Features.BlockStore/Api/Controllers/BlockStoreRPCController.cs, src/Features/Blockcore.Features.BlockStore/Api/Models/BlockStoreRouteEndPoint.cs, src/Features/Blockcore.Features.BlockStore/Blockcore.Features.BlockStore.csproj, src/Features/Blockcore.Features.RPC/RPCClient.cs, src/Tests/Blockcore.Features.BlockStore.Tests/BlockStoreControllerTests.cs
Added `gettxoutproof` RPC (0.20.0 RPC).
Checks if transactions are within block. Returns proof of transaction inclusion (raw MerkleBlock).
=> Added gettxoutproof RPC

src/Blockcore/Interfaces/UI/INavigationItem.cs, src/Features/Blockcore.Features.ColdStaking/UI/NavItem.cs, src/Features/Blockcore.Features.Miner/UI/NavItem.cs, src/Features/Blockcore.Features.NodeHost/UI/Shared/NavMenu.razor, src/Features/Blockcore.Features.Wallet/UI/NavItem.cs
Added a feature to allow the menu items to be configurable. 
The default order is:
=> Make nav menu order configurable

src/Blockcore/P2P/PeerAddressManager.cs
=> Improve loading of peers.json for corrupt peers.json file

src/Features/Blockcore.Features.ColdStaking/ColdStakingManager.cs
When I was resyncing my wallet I got this exception:
```
Blockcore.AsyncWork.AsyncProvider[0]
Unhandled exception for async delegate worker WalletSyncManager-blocksQueue.
System.NullReferenceException: Object reference not set to an instance of an object.
at Blockcore.Features.ColdStaking.ColdStakingManager.ProcessTransaction(Transaction transaction, Nullable`1 blockHeight, Block block, Boolean isPropagated) in C:\source\block-core\blockcore\src\Features\Blockcore.Features.ColdStaking\ColdStakingManager.cs:line 635
at Blockcore.Features.Wallet.WalletManager.ProcessBlock(Block block, ChainedHeader chainedHeader) in C:\source\block-core\blockcore\src\Features\Blockcore.Features.Wallet\WalletManager.cs:line 1103
at Blockcore.Features.Wallet.WalletSyncManager.OnProcessBlockAsync(Block block, …
```
=> Add null check to walletsync

src/Blockcore/Consensus/ScriptAddressReader.cs
If the transaction is a segwit, return the address.
=> Added segwit addresses to indexer.

src/Features/Blockcore.Features.Wallet/WalletManager.cs
The GetAddressBalance() method does not return any results when using a segwit address. This change fixes this.
=> Added the Bech32Address to GetAddressBalance()

src/Features/Blockcore.Features.Wallet/Api/Models/RequestModels.cs, src/Features/Blockcore.Features.Wallet/WalletTransactionHandler.cs, src/Tests/Blockcore.Features.Wallet.Tests/WalletControllerTest.cs
=> Port stratis fixes for OP_RETURN in transaction building

src/Features/Blockcore.Features.Wallet/Api/Controllers/WalletController.cs, src/Features/Blockcore.Features.Wallet/Api/Models/RequestModels.cs, src/Features/Blockcore.Features.Wallet/Interfaces/IWalletManager.cs, src/Features/Blockcore.Features.Wallet/WalletManager.cs
This is based on an implementation in the STRAX repro 
https://github.com/stratisproject/StratisFullNode/blob/master/src/Stratis.Bitcoin.Features.Wallet/WalletManager.cs#L374-#L396
=> Add API to retreive private key from wallet address

src/Features/Blockcore.Features.BlockStore/Api/Controllers/BlockStoreController.cs, src/Features/Blockcore.Features.BlockStore/Api/Models/BlockStoreRouteEndPoint.cs, src/Features/Blockcore.Features.BlockStore/Api/Models/UtxoModel.cs, src/Features/Blockcore.Features.BlockStore/BlockStoreFeature.cs, src/Features/Blockcore.Features.BlockStore/UtxoIndexing/ReconstructedCoinviewContext.cs, src/Features/Blockcore.Features.BlockStore/UtxoIndexing/UtxoIndexer.cs, src/Features/Blockcore.Features.Wallet/Api/Controllers/WalletController.cs, src/Features/Blockcore.Features.Wallet/Api/Models/RequestModels.cs, src/Features/Blockcore.Features.Wallet/Interfaces/IWalletManager.cs, src/Features/Blockcore.Features.Wallet/WalletManager.cs, src/Tests/Blockcore.Features.BlockStore.Tests/BlockStoreControllerTests.cs
This should be pretty close to the implemenation @zeptin did here https://github.com/stratisproject/StratisFullNode/commit/809186dd864908bc174f7db32105dedb4962c94a
Gonna mark this as draft as I still need to test and I think I should probably implement segwit addresses as well but open to initial feedback.
=> Port of stratx implementation of sweep

src/Blockcore/Consensus/Chain/ChainIndexer.cs
- This is used by the block indexer in the "blockcore-bitcore" repo.
=> Add support to retrieve genesis if empty hash is supplied

src/Tests/Blockcore.Features.Wallet.Tests/WalletManagerTest.cs, src/Tests/Blockcore.Features.Wallet.Tests/WalletStoreTest.cs
Fixes #210 
A couple of different issues with these tests:
1) LiteDB has some rounding behaviour for datetime's which if you are using LiteDB for a wallet you should be aware of. This was causing tests to fail.
2) There was a couple of tests that used test data that made assumption of date/time locality. I corrected those to be explicit.
=> Fix wallet unit tests

src/Networks/Blockcore.Networks.City/Networks/CityMain.cs, src/Networks/Blockcore.Networks.City/Networks/Rules/CityCheckPosUtxosetRule.cs
- Planned upgrade to the City Chain network with a consensus change that divides the coinbase reward by 10, at block height 1 111 111.
=> Update coinbase consensus for City Chain

src/Networks/Blockcore.Networks.Xds/XdsMain.cs
This is a soft fork change to the XDS consensus rules to make it POS only chain in order to eliminate the pos only exploit 
Currently the chain is at block 165064 so it will kick-in in about 1.5 days. 
This is mandatory upgrade for miners regular clients are not effected only (but should upgrade to be sure to be on the right side of the fork in case pow miners are still trying to miner)
There is a secondary experimental chain currently in testing that will be deployed in a few month to allow back POW in a more strict manner (every POW must be followed by a POS and vise versa)
=> Set XDS last POW Block to 165_500

src/Blockcore/Connection/ConnectionManagerBehavior.cs
peer connection failure is very annoying, it keep spamming "information" log on console
changed its log level to debug instead
=> peer connection failure moved to debug instead of information

src/Features/Blockcore.Features.NodeHost/UI/Pages/Index.razor, src/Features/Blockcore.Features.Wallet/Events/TransactionSpent.cs, src/Features/Blockcore.Features.Wallet/UI/Pages/WalletView.razor, src/Features/Blockcore.Features.Wallet/UI/Pages/Wallets.razor, src/Features/Blockcore.Features.Wallet/WalletManager.cs
=> Subscribe to blocks and peers events on the ui

CHANGELOG.md, src/Node/Blockcore.Node/NodeBuilder.cs
- Ensures no DRY.
- X42 should not use the WatchOnlyWallet, not being maintained or used.
- Update the changelog.
=> Minor improvement to the NodeBuilder for test node.

src/Directory.Build.props, src/Features/Blockcore.Features.Wallet/Database/WalletStore.cs
- This is the smallest impact and quickest way to fix the issue with connections against sqlite database.
- Closes #299
=> Make sure that each query against database uses a new connection object

src/Networks/Blockcore.Networks.XRC/XRCMain.cs
- Lowercase is preferred for these data folders. The "Main" folder is capitalized though, but that's consistent.
=> Make the folder name for data lowercase

src/Networks/Blockcore.Networks.x42/x42Setup.cs
After the segwit deployment flag was set on the network to AlwaysActive, blocks before this checkpoint might not have segwit blocks and cause the node to stop syncing with error *PH' had missing services NODE_WITNESS, it will be enqueued again.*
=> x42 checkpoint added

src/Blockcore/Connection/Broadcasting/BroadcastTransactionStateChanedEntry.cs, src/Blockcore/Connection/Broadcasting/BroadcasterManager.cs
- There might be multiple issues with a transaction and if sent multiple times with different errors, the error did not update.
- Closes #312
=> Allow update of broadcast entry

src/Blockcore/Consensus/BlockInfo/Block.cs, src/Features/Blockcore.Features.Consensus/ConsensusFeature.cs
- Add the witness service on startup to the node.
- Refactor the "WithOptions" method to clearly state conditions for logic.
- Closes #320
=> Add witness service always

src/Features/Blockcore.Features.RPC/RPCClient.cs, src/Features/Blockcore.Features.Wallet/Api/Controllers/WalletRPCController.cs, src/Tests/Blockcore.IntegrationTests/API/ApiSteps.cs, src/Tests/Blockcore.IntegrationTests/RPC/RPCTestsMutable.cs
There should be a better way to determine the fee of the network but until then, I've added this so chains like XDS that have custom fee of `AbsoluteMinimum` consensus so a custom fee can be passed in the RPC.
=> Added optional fee and segwit parameters to RPC

src/Networks/Blockcore.Networks.XRC/Rules/XRCHeaderVersionRule.cs, src/Networks/Blockcore.Networks.XRC/XRCMain.cs
For the XRC integration, a HeaderVersionRule was missing and thus couldn't be used to mine blocks.
This adds a HeaderVersionRule, doing the same thing that Bitcoin version does for now.
=> XRC: Add missing HeaderVersionRule

src/Features/Persistence/Blockcore.Persistence.RocksDb/Blockcore.Persistence.RocksDb.csproj, src/Node/Blockcore.Node/Properties/launchSettings.json
- Replaces the existing RocksDB library that has not been updated since 2019.
- Needs verification by others, please run and verify.
=> Migrate to Blockcore.RocksDB

src/Blockcore/Consensus/Chain/ChainedHeaderTree.cs, src/Blockcore/Consensus/ConsensusManager.cs
- "ChainedBlocksDataBytes" was not really used, but required loading of all headers on startup. Removed to improve performance from 52 seconds to 42 seconds.
- This was discovered independent of https://github.com/stratisproject/StratisFullNode/pull/233, but linking to that issue to help Stratis and Blockcore-based blockchains to take the improvement.
- #337
=> Remove the ChainedBlocksDataBytes

src/Features/Persistence/Blockcore.Persistence.RocksDb/Blockcore.Persistence.RocksDb.csproj
- Enables Mac support without manual dependency installation.
- Linux still require some dependencies to be installed to use RocksDB.
=> Update to latest RocksDB package

src/Blockcore/Base/BaseFeature.cs, src/Features/Blockcore.Features.Consensus/ConsensusFeature.cs, src/Features/Blockcore.Features.Consensus/PosConsensusFeature.cs, src/Features/Blockcore.Features.Consensus/PowConsensusFeature.cs, src/Features/Blockcore.Features.Consensus/Rules/CommonRules/SetActivationDeploymentsPartialValidationRule.cs
- The deployment flags are cached when calculated as new blocks come in.
- The deployment flags are read from cache at startup, as they cannot have changed since shutdown.
- This gives a very big improvement on node startup.
- #337
=> Cache the deployment flags to improve startup

src/Directory.Build.props, src/Networks/Blockcore.Networks.RoyalSportsCity/Networks/Deployments/RoyalSportsCityBIP9Deployments.cs, src/Networks/Blockcore.Networks.RoyalSportsCity/Networks/RoyalSportsCityMain.cs, src/Networks/Blockcore.Networks.SeniorBlockCoin/Networks/Deployments/SeniorBlockCoinBIP9Deployments.cs, src/Networks/Blockcore.Networks.SeniorBlockCoin/Networks/SeniorBlockCoinMain.cs
- This makes the BIP deployments active from genesis.
- This fixes issue where nodes disconnected from other nodes that does not signal Segwit support.
=> Updates to BIP deployments for RSC and SBC

src/Blockcore/Interfaces/INetworkWeight.cs, src/Features/Blockcore.Features.Miner/Api/Controllers/StakingController.cs, src/Features/Blockcore.Features.Miner/Api/Models/GetNetworkStakingInfoModel.cs, src/Features/Blockcore.Features.Miner/Blockcore.Features.Miner.csproj, src/Features/Blockcore.Features.Miner/MiningFeature.cs, src/Features/Blockcore.Features.Miner/Staking/PosMinting.cs, src/Features/Blockcore.Features.RPC/Controllers/FullNodeController.cs, src/Features/Blockcore.Features.RPC/Models/BlockchainInfoModel.cs, src/Node/Blockcore.Node/Properties/launchSettings.json, src/Tests/Blockcore.Features.Miner.Tests/Controllers/StakingControllerTest.cs
Endpoints to get the POS network difficulty to be used with the indexer for this issue
https://github.com/block-core/blockcore-indexer/issues/56
There are two approaches this can go:
- the approach of this PR where we have an additional endpoint for the POS difficulty and the current network weight.
- adding the network weight and difficulty to each block on the api method `GetBlock` (then on the explorer we can display the network weight on each block)
(note the difficulty on POS is calculated slightly differently when it comes to calculating the network weight)
=> Add endpoint to return the network weight for POS chains

src/Blockcore/Base/BaseFeature.cs, src/Blockcore/Configuration/NodeSettings.cs
Right now when we set a debug param we always display the bellow output, this PR requires users to specifically set debug=tasks to show it
=> Display background tasks diagnostics only with debug=tasks param

src/Networks/Blockcore.Networks.XRC/Blockcore.Networks.XRC.csproj, src/Networks/Blockcore.Networks.XRC/Consensus/XRCBlockHeader.cs, src/Networks/Blockcore.Networks.XRC/Consensus/XRCCoinType.cs, src/Networks/Blockcore.Networks.XRC/Consensus/XRCConsensus.cs, src/Networks/Blockcore.Networks.XRC/Consensus/XRCConsensusFactory.cs, src/Networks/Blockcore.Networks.XRC/Consensus/XRCConsensusProtocol.cs, src/Networks/Blockcore.Networks.XRC/Consensus/XRCNetwork.cs, src/Networks/Blockcore.Networks.XRC/Crypto/XRCHashX11.cs, src/Networks/Blockcore.Networks.XRC/Rules/XRCCheckDifficultyPowRule.cs, src/Networks/Blockcore.Networks.XRC/XRCMain.cs, src/Networks/Blockcore.Networks.XRC/XRCRegTest.cs, src/Networks/Blockcore.Networks.XRC/XRCTest.cs
Hello,
there was a new hardfork of XRC from block 136136 which changed algo of XRC from X13 to X11 and it is using now DigiShield POW Retarget every next block.
This pull request is there because of compatibility of Blockcore with this change.
Thank you for merge.
=> XRC HardFork - X11, DigiShield POW algo

.github/workflows/build.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, .github/workflows/test.yml, src/Directory.Build.props, src/Tests/Blockcore.Tests/P2P/NetworkPeerServerTests.cs
This PR will upgrade the blockcore project to dotnet 8
1 fix was required for the test case Validate_AllowClientConnection_State
There are no library updates, however there is a need to upgrade all vulenrable and deprecated libraries.
I think due to the number of changes required for updating each library, it's worth creating seperate PR's for those
=> Dotnet8 Upgrade

src/Blockcore/Blockcore.csproj, src/Features/Blockcore.Features.BlockStore/AddressIndexing/AddressIndexRepository.cs, src/Features/Blockcore.Features.BlockStore/AddressIndexing/AddressIndexer.cs, src/Features/Blockcore.Features.BlockStore/AddressIndexing/AddressIndexerOutpointsRepository.cs, src/Tests/Blockcore.Features.BlockStore.Tests/AddressIndexerOutpointsRepositoryTests.cs, src/Tests/Blockcore.Features.BlockStore.Tests/AddressIndexerTests.cs
@dangershony @sondreb  
I am unable to understand why the Fork is not be rewinded, and why Block 10 still appears in the fork.
Please review the changes, and see if this is something we can fix, or if we leave LiteDB at the current version.
Please note that there are vulenrabilities reported on LiteDB, and this version i've picked is the first version that seems the most stable (most tests pass on BlocCore), when compared to any later version.  There are bugs with Transactions in LiteDB which must be resolved prior to any further upgrades of the library.
```
Failed Tests:
 CanIndexAddresses
 Source: AddressIndexerTests.cs line 72
 Duration: 6.2 sec
Message: 
Assert.Equal() Failure: Values differ
Expected: 70000
Actual:   60000
Stack Trace: 
AddressIndexerTests.CanIndexAddresses() line 159 …
```
=> Upgrade LiteDB@5.0.15
